version: "3.8"
services:
  server:
    build: ./server
    ports:
      - "4005:4005"
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=4005
    depends_on:
      - db
    volumes:
      - ./server:/app

  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
    depends_on:
      - server
    volumes:
      - ./client:/app

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  pgdata: